paths:
    templates: './templates/www'
    static: './static'
    build: './build'
    locale: './i18n'
    export: '/tmp'

templates: [
    'index.html',
    'media-policy.html',
    'privacy-statement.html',
    'coc.html',
    'participation-agreement.html',
    'volunteer-roles.html',
    'volunteer-session-chairs.html',
    'cz/index.html',
    'cz/2017/index.html',
    'cz/2017/roadshow-prague.html',
    'cz/2018/index.html',
    'cz/2019/index.html',
    'sk/2017/roadshow-bratislava.html',
    'us/index.html',
    'us/2018/index.html',
    'in/index.html',
    'in/2018/index.html',
    'in/2019/index.html',
    'devconf-error-cfp-not-open.html',
    '404.html'
]

locales: ['en_US', 'cs_CZ', 'sk_SK']
